name: kingsfam
description: Christian communities.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+44

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependency_overrides:
# firebase_messaging_platform_interface: 3.1.6
# firebase_crashlytics_platform_interface: 3.1.13
# cloud_firestore_platform_interface: 5.4.13
# firebase_auth_platform_interface: 6.1.11
# firebase_storage_platform_interface: 4.0.14
# cloud_functions_platform_interface: 5.0.21
# firebase_analytics_platform_interface: 3.0.5
# firebase_remote_config_platform_interface: 1.0.5
# firebase_dynamic_links_platform_interface: 0.2.0+5
# firebase_performance_platform_interface: 0.1.0+5
# firebase_app_installations: ^0.2.1+8

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  date_time_picker: ^2.1.0

  enum_to_string: ^2.0.1

  flutter_bloc: ^7.1.0
  equatable: ^2.0.3

  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.6 # was 4.0.0

  google_sign_in: ^5.4.4
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.1

  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.11 #firebase_storage: ^11.0.10

  provider: ^6.0.5
  uuid: ^3.0.4
  path_provider: ^2.0.2
  flutter_image_compress: ^1.0.0
  image_picker: ^0.8.1+3
  cached_network_image: ^3.0.0

  # file_picker: ^4.1.4
  # image_editor_plus: ^0.1.5 this thing litterly causes my app to crash
  image_cropper: ^1.4.1
  video_player:

  shared_preferences: ^2.0.6

  font_awesome_flutter: ^10.1.0
  flare_flutter: ^3.0.2

  timeago: ^3.1.0
  intl: ^0.17.0

  permission_handler: ^10.0.0

  scrollable_positioned_list: ^0.3.5
  video_thumbnail: ^0.5.0
  google_mobile_ads: ^2.3.0 #^2.0.1 pod update Google-Mobile-Ads-SDK
  url_launcher: ^6.0.8
  flutter_svg: ^1.1.2

  rename:
  get: ^4.6.1
  google_fonts: ^3.0.1

  streaming_shared_preferences: ^2.0.0
  json_annotation: ^4.6.0
  visibility_detector: ^0.3.3
  helpers: ^1.1.4
  carousel_slider: ^4.1.1
  new_version: ^0.3.1
  simple_link_preview: ^1.0.2
  iconsax: ^0.0.8
  flutter_local_notifications: ^12.0.4
  firebase_dynamic_links: ^5.0.0
  # camera: ^0.10.1
  flutter_native_splash: ^2.2.9
  giphy_get: ^2.0.2
  flutter_dotenv: ^5.0.2
  video_trimmer: ^2.0.1
  like_button: ^2.0.5

  #agora_rtc_engine: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

# commands to run in terminal to gen spalsh screen
# flutter clean
# flutter pub get
# flutter pub run flutter_native_splash:create
# flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/kf_crown_black_960_960.png
  image_dark: assets/kf_crown_white_960_960.png
  color: "#FFFFFF"
  color_dark: "#101010"
  icon_background_color: "#FFFFFF"
  icon_background_color_dark: "#101010"


  android_12:
    image: assets/kf_crown_black_960_960.png
    image_dark: assets/kf_crown_white_960_960.png
    color: "#FFFFFF"
    color_dark: "#101010"
    icon_background_color: "#101010"
    icon_background_color_dark: "#FFFFFF"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/kf_crown_white_960_960.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon_transparent.png
    - assets/share_post_temp.png
    - assets/placeholder_kf.png
    # SVG's are below
    # ANIMATIONS are below
    - .env
