import 'package:kingsfam/extensions/hexcolor.dart';

const String stripeParishableKey = "pk_live_51LepZfCJ9MK5xgXMBHmITl7eKyBFuvqvfDqGuWhHCxUHaPHLQjvu9t9UEllAS2pujx7w1JVTBepaVgQjbwNwL6CI00dZTbeI9h";
const String stripeParishableKeyTest = "pk_test_51LepZfCJ9MK5xgXMBLiQf7dhI8rZPN2tdAE1UC9KYBfuIJkTbVotfj2sWKRwrJ4S94sbehQR0y3sI6ZDvmDSa9UB0007UhxSBA";
HexColor hc = HexColor();